name: Tests

on:
  - push
  - pull_request

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install linting dependencies
        run: poetry install --only lint

      - name: Check Linting
        run: poetry run black --check mercapi/ tests/

  test:
    name: Unit test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest
